name: "TFC Create (plan+apply)"
on:
  workflow_dispatch: {}

env:
  TF_CLOUD_ORGANIZATION: "Kiwi_Num_Slide"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "three-tier-dev"
  CONFIG_DIRECTORY: "./"

jobs:
  terraform:
    name: "Create infra via TFC API"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Configuration
        id: upload
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.2.0
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Create Run (plan+apply)
        id: run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.2.0
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
          message: "Create run from GitHub Actions ${{ github.sha }}"

      - name: Auto-Apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.2.0
        if: fromJSON(steps.run.outputs.payload).data.attributes.actions.IsConfirmable
        with:
          run: ${{ steps.run.outputs.run_id }}
          comment: "Apply triggered by GitHub Actions"

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Notify via SNS (Infra created)
        run: |
          aws sns publish \
            --topic-arn "$SNS_TOPIC_ARN" \
            --subject "âœ… Infra UP" \
            --message "The AWS infra has been successfully created via GitHub Actions."
        env:
          SNS_TOPIC_ARN: ${{ secrets.SNS_TOPIC_ARN }}
